export enum Env {
  SAFE_AREA_INSET_TOP,
  SAFE_AREA_INSET_RIGHT,
  SAFE_AREA_INSET_BOTTOM,
  SAFE_AREA_INSET_LEFT,

  TITLEBAR_AREA_X,
  TITLEBAR_AREA_Y,
  TITLEBAR_AREA_WIDTH,
  TITLEBAR_AREA_HEIGHT,

  KEYBOARD_INSET_TOP,
  KEYBOARD_INSET_RIGHT,
  KEYBOARD_INSET_BOTTOM,
  KEYBOARD_INSET_LEFT,
  KEYBOARD_INSET_WIDTH,
  KEYBOARD_INSET_HEIGHT,
}
