import { Accents } from "../enums";

export const ACCENTS_CODES: string[] = [
  Accents.QUOTE,
  Accents.BRACKET_LEFT,
  Accents.DIAERESIS,
  Accents.CARET,
];

export const ACCENTS_MAP = {
  // ´
  á: { base: "a", accent: "´" },
  é: { base: "e", accent: "´" },
  í: { base: "i", accent: "´" },
  ó: { base: "o", accent: "´" },
  ú: { base: "u", accent: "´" },
  Á: { base: "A", accent: "´" },
  É: { base: "E", accent: "´" },
  Í: { base: "I", accent: "´" },
  Ó: { base: "O", accent: "´" },
  Ú: { base: "U", accent: "´" },
  // `
  à: { base: "a", accent: "`" },
  è: { base: "e", accent: "`" },
  ì: { base: "i", accent: "`" },
  ò: { base: "o", accent: "`" },
  ù: { base: "u", accent: "`" },
  À: { base: "A", accent: "`" },
  È: { base: "E", accent: "`" },
  Ì: { base: "I", accent: "`" },
  Ò: { base: "O", accent: "`" },
  Ù: { base: "U", accent: "`" },
  // ¨
  ä: { base: "a", accent: "¨" },
  ë: { base: "e", accent: "¨" },
  ï: { base: "i", accent: "¨" },
  ö: { base: "o", accent: "¨" },
  ü: { base: "u", accent: "¨" },
  Ä: { base: "A", accent: "¨" },
  Ë: { base: "E", accent: "¨" },
  Ï: { base: "I", accent: "¨" },
  Ö: { base: "O", accent: "¨" },
  Ü: { base: "U", accent: "¨" },
  // ^
  â: { base: "a", accent: "^" },
  ê: { base: "e", accent: "^" },
  î: { base: "i", accent: "^" },
  ô: { base: "o", accent: "^" },
  û: { base: "u", accent: "^" },
  Â: { base: "A", accent: "^" },
  Ê: { base: "E", accent: "^" },
  Î: { base: "I", accent: "^" },
  Ô: { base: "O", accent: "^" },
  Û: { base: "U", accent: "^" },
};

export const ACCENTS_COMBINATOR = {
  [Accents.QUOTE]: {
    a: "á",
    e: "é",
    i: "í",
    o: "ó",
    u: "ú",
    A: "Á",
    E: "É",
    I: "Í",
    O: "Ó",
    U: "Ú",
  },
  [Accents.BRACKET_LEFT]: {
    a: "à",
    e: "è",
    i: "ì",
    o: "ò",
    u: "ù",
    A: "À",
    E: "È",
    I: "Ì",
    O: "Ò",
    U: "Ù",
  },
  [Accents.DIAERESIS]: {
    a: "ä",
    e: "ë",
    i: "ï",
    o: "ö",
    u: "ü",
    A: "Ä",
    E: "Ë",
    I: "Ï",
    O: "Ö",
    U: "Ü",
  },
  [Accents.CARET]: {
    a: "â",
    e: "ê",
    i: "î",
    o: "ô",
    u: "û",
    A: "Â",
    E: "Ê",
    I: "Î",
    O: "Ô",
    U: "Û",
  },
};
