name: Build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    name: "tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Enable Corepack
        run: corepack enable

      - run: yarn install --immutable

      - name: run prettier checker
        run: yarn prettier:check

      - name: run tests
        run: yarn test

      - name: Publish package
        run: npx jsr publish --allow-dirty --dry-run
